### ISSUE TITLE
Modificaciones códigos P1

### ISSUE THREAD

**Issue by marisolosman** [LucianoAndrian/PronosticoClimatico2024#1]
Cambios para hacer

nombre variable modelo -> pp_modelo
model_signal -> pp_model_signal
model_noise -> pp_model_noise

añadir parametro mascara opcional de cordillera en ploteos (andes_mask?)
borra variables auxiliares una vez que no se usan mas

**Comment by marisolosman** [comment]
- cambiar nombre de variable acc_ca por acc

**Comment by LucianoAndrian** [comment]
listo
[Issue 1](https://github.com/LucianoAndrian/PronosticoClimatico2024/commit/9b9d510969f495912fd69e2327b17981521c39da)
